# frozen_string_literal: true

require 'fileutils'

module RubynCode
  module CLI
    # Installs a pinned launcher that bypasses rbenv/rvm version switching.
    #
    # When rubyn-code is installed as a gem, RubyGems generates a wrapper in
    # the Ruby version's bin dir (e.g. ~/.rbenv/versions/3.4.5/bin/rubyn-code)
    # with a shebang pointing to the correct Ruby. However, rbenv's shim at
    # ~/.rbenv/shims/rubyn-code intercepts the command and re-resolves Ruby
    # based on .ruby-version in the current directory — which breaks rubyn-code
    # when you cd into a project using a different Ruby.
    #
    # This setup creates a launcher in ~/.local/bin (which typically appears
    # before ~/.rbenv/shims in PATH) that calls the gem wrapper directly,
    # bypassing the shim entirely.
    class Setup
      INSTALL_DIR = File.expand_path('~/.local/bin')
      LAUNCHER_NAME = 'rubyn-code'

      def self.run
        new.run
      end

      def run
        gem_wrapper = find_gem_wrapper
        unless gem_wrapper
          warn 'Error: Could not find the rubyn-code gem wrapper.'
          warn 'Make sure rubyn-code is installed: gem install rubyn-code'
          exit 1
        end

        pinned_ruby = extract_ruby_from_wrapper(gem_wrapper)
        unless pinned_ruby
          warn "Error: Could not determine Ruby path from #{gem_wrapper}"
          exit 1
        end

        launcher_path = File.join(INSTALL_DIR, LAUNCHER_NAME)

        FileUtils.mkdir_p(INSTALL_DIR)
        write_launcher(launcher_path, gem_wrapper, pinned_ruby)
        File.chmod(0o755, launcher_path)

        puts "Installed pinned launcher to #{launcher_path}"
        puts "  Ruby:   #{pinned_ruby}"
        puts "  Wrapper: #{gem_wrapper}"
        puts

        verify_path(launcher_path)
      end

      private

      def find_gem_wrapper
        # The gem wrapper lives in the same bin dir as the current Ruby
        ruby_bin = RbConfig::CONFIG['bindir']
        candidate = File.join(ruby_bin, LAUNCHER_NAME)
        return candidate if File.exist?(candidate)

        # Fallback: search gem paths
        Gem.path.each do |gem_path|
          bin = File.join(gem_path, 'bin', LAUNCHER_NAME)
          return bin if File.exist?(bin)
        end

        nil
      end

      def extract_ruby_from_wrapper(wrapper_path)
        first_line = File.open(wrapper_path, &:readline).strip
        if first_line.start_with?('#!')
          ruby_path = first_line.sub(/\A#!\s*/, '')
          return ruby_path if File.executable?(ruby_path)
        end

        # Fallback to the Ruby running this process
        RbConfig.ruby
      rescue EOFError
        nil
      end

      def write_launcher(path, gem_wrapper, pinned_ruby)
        ruby_version = File.basename(File.dirname(pinned_ruby, 2))
        File.write(path, <<~BASH)
          #!/usr/bin/env bash
          # Rubyn Code launcher — pinned to Ruby #{ruby_version}
          # Generated by: rubyn-code --setup
          # Bypasses rbenv/rvm so rubyn-code works in any project.
          #
          # Uses the pinned Ruby directly (not /usr/bin/env ruby) to avoid
          # rbenv resolving to a different Ruby based on .ruby-version.
          #
          # To regenerate: rubyn-code --setup
          # To remove:     rm #{path}
          exec "#{pinned_ruby}" "#{gem_wrapper}" "$@"
        BASH
      end

      def verify_path(launcher_path)
        install_dir = File.dirname(launcher_path)
        path_dirs = ENV['PATH'].split(File::PATH_SEPARATOR)
        shim_index = path_dirs.index { |d| d.include?('rbenv/shims') || d.include?('rvm') }
        install_index = path_dirs.index(install_dir)

        if install_index.nil?
          puts "Warning: #{install_dir} is not in your PATH."
          puts 'Add this to your shell profile:'
          puts "  export PATH=\"#{install_dir}:$PATH\""
        elsif shim_index && install_index > shim_index
          puts "Warning: #{install_dir} comes AFTER rbenv shims in PATH."
          puts 'Move it before the shims in your shell profile so it takes priority.'
        else
          puts "PATH looks good — #{install_dir} takes priority over version manager shims."
        end
      end
    end
  end
end
